name: Merge

on:
  workflow_call:

env:
  GH_TOKEN: ${{ github.token }}
  MERGE_QUEUE_REPO: jakeprime/merge-queue
  PROJECT_REPO: ${{ github.repository }}
  PR_NUMBER: ${{ github.event.issue.number }}

permissions:
  contents: read

jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ env.GH_TOKEN }}
          repository: ${{ env.MERGE_QUEUE_REPO }}
          path: merge-queue
          ref: typescript

      - name: Run
        id: run
        uses: ./merge-queue/

      - name: Print Output
        id: output
        run: echo "${{ steps.run.outputs.message }}"
