name: Merge

on:
  workflow_call:

env:
  GH_TOKEN: ${{ github.token }}
  MERGE_QUEUE_REPO: jakeprime/merge-queue
  PROJECT_REPO: ${{ github.repository }}
  PR_NUMBER: ${{ github.event.issue.number }}

permissions:
  contents: read

jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest

    steps:
      # we need to checkout 3 git branches:
      #  - merge-queue-repo: the main branch of the queue where these scripts live
      #  - merge-queue-state: this project's own merge queue state branch
      #  - project: where the work is and the merging will happen
      - name: Checkout merge queue repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.MERGE_QUEUE_REPO }}
          token: ${{ secrets.MERGE_QUEUE_TOKEN }}
          path: merge-queue-repo

      - name: Checkout queue state
        uses: actions/checkout@v4
        with:
          repository: ${{ env.MERGE_QUEUE_REPO }}
          token: ${{ secrets.MERGE_QUEUE_TOKEN }}
          path: merge-queue-state
          ref: ${{ env.PROJECT_REPO }}
          fetch-depth: 0

      - name: Checkout project
        uses: actions/checkout@v4
        with:
          path: project
          fetch-depth: 0

      - name: Run
        id: run
        uses: ./merge-queue/

      - name: Print Output
        id: output
        run: echo "${{ steps.run.outputs.message }}"
